version: '3.8'
services:
  db:
    image: postgres:15
    container_name: retail-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: First1@infamily
      POSTGRES_DB: retail_forecast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: retail-backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:First1%40infamily@db:5432/retail_forecast
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: retail-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
volumes:
  postgres_data:
